### ISSUE TITLE
1.1, 1.2 and 1.3 jars are missing

### ISSUE THREAD

**Issue by danclarke** [aws/aws-greengrass-core-sdk-java#1]
The documentation refers to GreengrassJavaSDK-1.3.jar but only GreengrassJavaSDK-1.0.jar is present in the repo. Also the SDKs from Maven for Greengrass seem to be completely different to the jar bundled in this repo: https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk-greengrass

**Comment by MikeDombo** [comment]
The GreengrassJavaSDK-1.0.jar file will be the latest version. Earlier versions should not be needed as the current version ought to be compatible with all Greengrass versions.
