### ISSUE TITLE
Error loading class file - hello world example

### ISSUE THREAD

**Issue by veslav3** [aws/aws-greengrass-core-sdk-java#2]
```Error loading class com.amazonaws.greengrass.examples.HelloWorld: com/amazonaws/greengrass/common/EnvVars: java.lang.NoClassDefFoundError
java.lang.NoClassDefFoundError: com/amazonaws/greengrass/common/EnvVars
	at com.amazonaws.greengrass.javasdk.IotDataClient.<clinit>(IotDataClient.java:39)
	at com.amazonaws.greengrass.examples.PublishHelloWorld.<init>(PublishHelloWorld.java:10)
	at com.amazonaws.greengrass.examples.HelloWorld.<clinit>(HelloWorld.java:24)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
Caused by: java.lang.ClassNotFoundException: com.amazonaws.greengrass.common.EnvVars
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 5 more
```

What am I doing wrong? I followed all the instructions in the readme and changed the handler location to "com.amazonaws.greengrass.examples.HelloWorld::handleRequest".

**Comment by veslav3** [comment]
My guess is that the web console is not able to test the greengrass lambda functions.

**Comment by veslav3** [comment]
By now I am almost 100% sure that was the issue. Is there any way to test a lambda function locally?

**Comment by timmattison** [comment]
Yes, this is something that can be done but requires extra plumbing. I want to support this with my AWS samples library Cloud Device Drivers for Greengrass - https://github.com/aws-samples/aws-greengrass-lambda-functions/tree/master/foundation/CDDBaselineJava - but haven't finished that work yet. Could you open this issue over there? There is some support for it a while ago that I built but we can work on making sure it is up to date in that repo.

**Comment by timmattison** [comment]
Found the code here - https://github.com/aws-samples/aws-greengrass-lambda-functions/blob/92477e9b0426faffb170c9637d4b3fe9d0f034aa/foundation/CDDBaselineJava/src/main/java/com/awslabs/aws/iot/greengrass/cdd/BaselineAppInterface.java#L35

Essentially Cloud Device Drivers (CDD) implements the static startup block for you, it catches this NoClassDefFoundError exception and then replaces the Greengrass communication code with a dummy module.

Feel free to borrow this code for your projects if you don't want to use CDD.

**Comment by veslav3** [comment]
Hi @timmattison, I'd love to at some point. At the moment I'm not really actively working on Greengrass because my colleague is figuring it out. We can keep in touch on Twitter if you like so I will send you a message when I have more time and get more involved with Greengrass. At the moment I literally just worked with it for a week and then switched back to IoT Core.

**Comment by timmattison** [comment]
No worries. They can ping me there as well if they need. Happy to help whenever you need it.

**Comment by jainshikha** [comment]
Hi,
@timmattison @veslav3 ,
Is that issue resolved? Am also facing the same issue.
Please let me know the solution if the issue is fixed.

**Comment by veslav3** [comment]
@jainshikha not sure, I can have a look with you if I can help in any way (contact info is on my profile). But for me the issue is closed now.
