### ISSUE TITLE
Compatibility-Error in HelloWorld-Sample

### ISSUE THREAD

**Issue by MaxKemmler** [aws/aws-greengrass-core-sdk-java#3]
Hey guys,

After I already proceeded the first steps Tutorial for Greengrass (with Python).
Now i wanted to try out the Greengrass Core SDK for Java. 
I set up everything according to the readme-file. Apparently the provided Lambda-Function is not delivering the expected results- due to no message showing up in the IoT-Core-Test window.

After a few hours of investigation in the logging files i discovered the following Error in the user log files:

`[2020-01-25T18:38:44.516+01:00][ERROR]-Java runtime initialization failed: com.amazonaws.greengrass.runtime.exception.InvalidInterfaceVersionException: There was a version incompatibility between the Greengrass SDK used by your function [arn:aws:lambda:eu-central-1:343452210088:function:BuenosDias:1] and the Greengrass Core. Please visit the AWS Greengrass Developer Guide for version compatibility information
`

I was tried to deploy the lambda with the newest and an older version (1.4.0) of the greengrass-sdk- but the error remains the same. My curent GGC-Version is 1.9.4.

I hope you guys can help me out here

**Comment by MikeDombo** [comment]
You need to use GGC 1.10.0 with the 1.4.x versions of the Java SDK. Here's a link to the 1.3.x tag which should work for 1.9.4 of GGC: https://github.com/aws/aws-greengrass-core-sdk-java/tree/v1.3.1.

Though if you're just starting to use Greengrass and trying to get things to work, then I would recommend that you also upgrade your GGC version to the latest 1.10.0.
