### ISSUE TITLE
Can not find com.amazonaws.greengrass.javasdk.IotDataClient

### ISSUE THREAD

**Issue by larryxia-ddl** [aws/aws-greengrass-core-sdk-java#4]
In the Helloworld example, it use class com.amazonaws.greengrass.javasdk.IotDataClient. 
From which project this class comes from. what is the different beween IotDataClient and AWSIoTMQTTClient. Is there any document of this class.

**Comment by MikeDombo** [comment]
The IoTDataClient is available in the jar library of this repository: https://github.com/aws/aws-greengrass-core-sdk-java/blob/master/sdk/GreengrassJavaSDK.jar.

The AWSIoTMQTTClient is provided by the AWS IoT Device SDK. The IoTDataClient is meant to be used within a lambda function running on Greengrass, whereas the AWSIoTMQTTClient is used on devices which connect to IoT Core or to Greengrass. 

API documentation for the IoTDataClient is available here: https://aws.github.io/aws-greengrass-core-sdk-java/com/amazonaws/greengrass/javasdk/IotDataClient.html.

Please close the issue if that has answered you questions, or reply if you have more questions.

**Comment by 5teven-tian** [comment]
Hi ,

Will GreengrassJavaSDK.jar have its own pom information (groupId ,artifactId and so on) ?

I can not find it in the Maven repository.

any helps welcome

**Comment by MikeDombo** [comment]
Hello Steven,
I'm sorry, but it is not available from maven central or any other repository. You'll need to download the jar file from this repo in order to use the SDK.

Thanks

**Comment by 5teven-tian** [comment]
> Hello Steven,
> I'm sorry, but it is not available from maven central or any other repository. You'll need to download the jar file from this repo in order to use the SDK.
> 
> Thanks

Okay, Thanks for your quick response.

**Comment by emaayan** [comment]
> Hello Steven,
> I'm sorry, but it is not available from maven central or any other repository. You'll need to download the jar file from this repo in order to use the SDK.
> 
> Thanks

is there a reason for this? this is a problem because the jar also includes classes from slf4j, jackson and validation, which could create classpath issues when integrated in a project that does contain those.
