### ISSUE TITLE
 Can we run this Java SDK for Android App?

### ISSUE THREAD

**Issue by AagamMehta** [aws/aws-greengrass-core-sdk-java#6]
Hello,
I am an embedded developer. I have designed an IoT system with few micro-controllers (as IoT Device) and Raspberry Pi (as GreenGrassCore). I can successfully communicate between devices (via core) through MQTT pub-sub (Note - Since all these devices are connected on the same network the communication works irrespective of the availability of internet). Now, to move a step ahead I am learning Android and communicate messages from/to Android App to IoT Devices (via GreenGrassCore). To test the feasibility I used the Python SDK for GreenGrass and ran the sample code on Laptop and it executed successfully as expected. The communication worked with or without the availability of the Internet. Now I want the same thing to be coded for Android. Is the Java SDK the correct thing to start from? If yes, can you specify some examples and developer guide for GreenGrassCommunication? If no, can you please help with an alternate way around to make it work?

Thanking you in advance.

**Comment by MikeDombo** [comment]
Can you explain how it worked with Python? These SDKs with "greengrass-core" in their name *only* work when running on the same device that is running Greengrass itself. These SDKs only work when being run as a a lambda function on Greengrass. 

If you want to communicate between Greengrass and Android or any other device, you will just need a MQTT client which there are several options, though none provided by AWS support Android, so you will need to use another one.

Once you have a MQTT client for Android, have a look at https://docs.aws.amazon.com/greengrass/latest/developerguide/module4.html this module which shows you how to configure devices to talk to Greengrass using MQTT.

**Comment by AagamMehta** [comment]
Lemme specify the complete setup that we have tested and thereby explain the requirement for better clarity.

For testing the Offline Communication between IoT devices in the same network using Greengrass Core as an Offline Broker, we followed [Module 5 : Interacting with device shadows](https://docs.aws.amazon.com/greengrass/latest/developerguide/module5.html) of AWS IoT Greengrass.

![bd-ggc](https://user-images.githubusercontent.com/43824188/88776048-1925bf00-d1a3-11ea-8de1-d869cef50460.png)

As shown in the above diagram, Light switch device and Traffic light device communicate with each other even when there is no Internet connectivity. To suit our application, we modified the code (attached in the zipped folder below) of Light switch device (Original Code - [lightController.py](https://github.com/aws/aws-greengrass-core-sdk-python/blob/master/examples/TrafficLight/lightController.py) ; Modified Code - [lightController.zip](https://github.com/aws/aws-iot-device-sdk-java-v2/files/4993640/lightController.zip)) and instead of having another Laptop as an IoT Device for Traffic light device, we used ESP32 micro-controller running custom Amazon FreeRTOS code (which subscribes to a predefined topic and prints the received messages).


![LSU](https://user-images.githubusercontent.com/43824188/88776987-58a0db00-d1a4-11ea-9832-910b5d4b3e40.png)

In the above picture, the left console prints the logs of the lightController.py file (modified to publish a value variable to predefined topic) is running on Laptop and the right console is the Serial Monitor of the IoT Device (ESP32) running Amazon FreeRTOS. There is a Raspberry Pi 3B+ which is running Greengrass Core Software. These 3 devices are on the same WiFi network. Here, Laptop is the publisher which publishes MQTT messages every 20 seconds to a pre-defined topic. ESP32 is the subscriber which has subscribed to that pre-defined topic. Raspberry Pi acts as the Offline MQTT Broker when there is no internet connectivity. We tested this setup with and without Internet connectivity. When there is no internet connection the messages are still communicated from Laptop (publisher) to the IoT Device (Subscriber) via GreenGrass Core (Raspberry Pi) where Greengrass Core acts as Offline MQTT Broker to facilitate the communication.

This setup has worked seamlessly.

Now, we want to have a Mobile App (Android) as the Publisher instead of a Laptop. Laptop used [aws-iot-device-sdk-python](https://github.com/aws/aws-iot-device-sdk-python) but the same cannot be used in an Android App. Hence, we want to find a similar aws-iot-device-sdk to make it run on Android. We found that there is also aws-iot-device-sdk-java-v2 which has Greengrass Sample Code similar to AWS-IoT-Device SDK for Python.

Queries
1) Is the aws-iot-device-sdk-java or aws-iot-device-sdk-java-v2 the correct way ahead for an Android App?
2) If yes, then how to execute the GreenGrass Communication Sample Code in Android? A developer guide will be highly helpful for this.
3) If no, then what is the correct way ahead to develop an Android App to communicate locally with GreenGrassCore and other IoT devices?

Really hoping guidance on this since I ain't able to find suitable guide online. Thanking you in advance.

**Comment by MikeDombo** [comment]
According to the README of [aws-iot-device-sdk-java-v2](https://github.com/aws/aws-iot-device-sdk-java-v2), yes it does support Android from API level 26.

They even have a Greengrass basic discovery example: https://github.com/aws/aws-iot-device-sdk-java-v2/tree/master/samples/Greengrass/src/main/java.

But since you were able to get it to work with Python, the setup will be much the same for Java and Android. You will need to create an IoT Thing and certificate for the Android device and associate it with the Greengrass Group. Then you can use discovery to find the Greengrass device and the Group CA. Using all that information you can create the MQTT client to then send and receive messages to Greengrass.
